# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/shift/otter/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),otter)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,f0994fdf5c91de8e490599da62f7ed9174eb6eb8)
$(call add-radio-file-sha1-checked,radio/modem.img,f18e6f0edc4e79e865fc9cdbe393120f410c9163)
$(call add-radio-file-sha1-checked,radio/abl.img,6be18b34c7560b3d7904d40820de157cbb2ed7bc)
$(call add-radio-file-sha1-checked,radio/aop.img,c66f617fe5188a1cd9ceb1af0910d87e8c90ce9f)
$(call add-radio-file-sha1-checked,radio/cpucp.img,e38c7f3f1571cf7393797c390501eb129f7fe955)
$(call add-radio-file-sha1-checked,radio/devcfg.img,997ef2e68429772d19a40d4fc59dea7ea300c695)
$(call add-radio-file-sha1-checked,radio/dsp.img,1edfc1076502abe8efd925e0908dd2ca4c062a3a)
$(call add-radio-file-sha1-checked,radio/featenabler.img,f62c12be51ebce82f1de8eb2b83b6e7605736ca5)
$(call add-radio-file-sha1-checked,radio/hyp.img,000565b73c512a357ea00472f6ffede8dec9d96f)
$(call add-radio-file-sha1-checked,radio/imagefv.img,4136b376070bd435b91927e718d9b02272b72db9)
$(call add-radio-file-sha1-checked,radio/keymaster.img,25d2e1da8d32bf7f6be84c99c9ea7bccac63e3c9)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,078875d599f30e4cd25eef7a17f68b682dbfca7b)
$(call add-radio-file-sha1-checked,radio/qupfw.img,806571444723de78643a13afa4777e62104a5d91)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,c59e88c647d8eec8e7ee43305bccf6271149d248)
$(call add-radio-file-sha1-checked,radio/tz.img,3ce53c98e6ed9b34a3d3a39218aa3ea1ea1671f6)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,790ccea0c08a84cfd84ab9279165ab8a903d4163)
$(call add-radio-file-sha1-checked,radio/xbl.img,89243d12d05feac3c2dc07c42b59335274c6abf0)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,5f229aed8c25b861474359a6e972df26a679976c)

endif
