# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/shift/otter/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    bluetooth \
    modem \
    abl \
    aop \
    cpucp \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    multiimgoem \
    qupfw \
    qweslicstore \
    shrm \
    tz \
    uefisecapp \
    xbl \
    xbl_config
